name: ocean
favicon: null
layout_spectrum: 0.10338
typography_spectrum: 0.76363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070c2a'
    - '#dc3282'
    - '#722867'
    - '#608396'
    - '#3f569c'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
