name: ocean
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2f52ac'
    - '#62dce7'
    - '#39a6c5'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
