name: architect
favicon: null
layout_spectrum: 0.3093511101324111
typography_spectrum: 0.5476621056441218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2722658487036824
  lightness: 0.044862650567665696
  saturation: 0.9158499708864838
  rhythmicContrast: 0.7477755295112729
purpose: []
