name: architect
favicon: null
layout_spectrum: 0.30452
typography_spectrum: 0.19311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#475562'
    - '#aa8853'
    - '#a4aab6'
    - '#e3bd82'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
